export const UPDATE_LOGIN='update_login'
export const UPDATE_SHOP_DETAILS='update_shop_details'
export const UPDATE_ORDER_DETAILS='update_order_details'
export const ORDER_CONDITION='order_condition'
export const DELETE_ORDER='delete_order'